// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ComponentServiceLookupResponsePB.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ComponentServiceLookupResponsePB_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ComponentServiceLookupResponsePB_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ComponentServiceLookupResponsePB_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ComponentServiceLookupResponsePB_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ComponentServiceLookupResponsePB_2eproto;
namespace gravity {
class ComponentServiceLookupResponsePB;
struct ComponentServiceLookupResponsePBDefaultTypeInternal;
extern ComponentServiceLookupResponsePBDefaultTypeInternal _ComponentServiceLookupResponsePB_default_instance_;
}  // namespace gravity
PROTOBUF_NAMESPACE_OPEN
template<> ::gravity::ComponentServiceLookupResponsePB* Arena::CreateMaybeMessage<::gravity::ComponentServiceLookupResponsePB>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace gravity {

// ===================================================================

class ComponentServiceLookupResponsePB final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gravity.ComponentServiceLookupResponsePB) */ {
 public:
  inline ComponentServiceLookupResponsePB() : ComponentServiceLookupResponsePB(nullptr) {}
  ~ComponentServiceLookupResponsePB() override;
  explicit PROTOBUF_CONSTEXPR ComponentServiceLookupResponsePB(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ComponentServiceLookupResponsePB(const ComponentServiceLookupResponsePB& from);
  ComponentServiceLookupResponsePB(ComponentServiceLookupResponsePB&& from) noexcept
    : ComponentServiceLookupResponsePB() {
    *this = ::std::move(from);
  }

  inline ComponentServiceLookupResponsePB& operator=(const ComponentServiceLookupResponsePB& from) {
    CopyFrom(from);
    return *this;
  }
  inline ComponentServiceLookupResponsePB& operator=(ComponentServiceLookupResponsePB&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ComponentServiceLookupResponsePB& default_instance() {
    return *internal_default_instance();
  }
  static inline const ComponentServiceLookupResponsePB* internal_default_instance() {
    return reinterpret_cast<const ComponentServiceLookupResponsePB*>(
               &_ComponentServiceLookupResponsePB_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ComponentServiceLookupResponsePB& a, ComponentServiceLookupResponsePB& b) {
    a.Swap(&b);
  }
  inline void Swap(ComponentServiceLookupResponsePB* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ComponentServiceLookupResponsePB* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ComponentServiceLookupResponsePB* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ComponentServiceLookupResponsePB>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ComponentServiceLookupResponsePB& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ComponentServiceLookupResponsePB& from) {
    ComponentServiceLookupResponsePB::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ComponentServiceLookupResponsePB* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gravity.ComponentServiceLookupResponsePB";
  }
  protected:
  explicit ComponentServiceLookupResponsePB(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLookupIDFieldNumber = 1,
    kUrlFieldNumber = 2,
    kDomainIdFieldNumber = 3,
    kRegistrationTimeFieldNumber = 4,
  };
  // required string lookupID = 1;
  bool has_lookupid() const;
  private:
  bool _internal_has_lookupid() const;
  public:
  void clear_lookupid();
  const std::string& lookupid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_lookupid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_lookupid();
  PROTOBUF_NODISCARD std::string* release_lookupid();
  void set_allocated_lookupid(std::string* lookupid);
  private:
  const std::string& _internal_lookupid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_lookupid(const std::string& value);
  std::string* _internal_mutable_lookupid();
  public:

  // required string url = 2;
  bool has_url() const;
  private:
  bool _internal_has_url() const;
  public:
  void clear_url();
  const std::string& url() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_url(ArgT0&& arg0, ArgT... args);
  std::string* mutable_url();
  PROTOBUF_NODISCARD std::string* release_url();
  void set_allocated_url(std::string* url);
  private:
  const std::string& _internal_url() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_url(const std::string& value);
  std::string* _internal_mutable_url();
  public:

  // optional string domain_id = 3;
  bool has_domain_id() const;
  private:
  bool _internal_has_domain_id() const;
  public:
  void clear_domain_id();
  const std::string& domain_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_domain_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_domain_id();
  PROTOBUF_NODISCARD std::string* release_domain_id();
  void set_allocated_domain_id(std::string* domain_id);
  private:
  const std::string& _internal_domain_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_domain_id(const std::string& value);
  std::string* _internal_mutable_domain_id();
  public:

  // optional uint32 registration_time = 4;
  bool has_registration_time() const;
  private:
  bool _internal_has_registration_time() const;
  public:
  void clear_registration_time();
  uint32_t registration_time() const;
  void set_registration_time(uint32_t value);
  private:
  uint32_t _internal_registration_time() const;
  void _internal_set_registration_time(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:gravity.ComponentServiceLookupResponsePB)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr lookupid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr url_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr domain_id_;
    uint32_t registration_time_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ComponentServiceLookupResponsePB_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ComponentServiceLookupResponsePB

// required string lookupID = 1;
inline bool ComponentServiceLookupResponsePB::_internal_has_lookupid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ComponentServiceLookupResponsePB::has_lookupid() const {
  return _internal_has_lookupid();
}
inline void ComponentServiceLookupResponsePB::clear_lookupid() {
  _impl_.lookupid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ComponentServiceLookupResponsePB::lookupid() const {
  // @@protoc_insertion_point(field_get:gravity.ComponentServiceLookupResponsePB.lookupID)
  return _internal_lookupid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ComponentServiceLookupResponsePB::set_lookupid(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.lookupid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gravity.ComponentServiceLookupResponsePB.lookupID)
}
inline std::string* ComponentServiceLookupResponsePB::mutable_lookupid() {
  std::string* _s = _internal_mutable_lookupid();
  // @@protoc_insertion_point(field_mutable:gravity.ComponentServiceLookupResponsePB.lookupID)
  return _s;
}
inline const std::string& ComponentServiceLookupResponsePB::_internal_lookupid() const {
  return _impl_.lookupid_.Get();
}
inline void ComponentServiceLookupResponsePB::_internal_set_lookupid(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.lookupid_.Set(value, GetArenaForAllocation());
}
inline std::string* ComponentServiceLookupResponsePB::_internal_mutable_lookupid() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.lookupid_.Mutable(GetArenaForAllocation());
}
inline std::string* ComponentServiceLookupResponsePB::release_lookupid() {
  // @@protoc_insertion_point(field_release:gravity.ComponentServiceLookupResponsePB.lookupID)
  if (!_internal_has_lookupid()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.lookupid_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.lookupid_.IsDefault()) {
    _impl_.lookupid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ComponentServiceLookupResponsePB::set_allocated_lookupid(std::string* lookupid) {
  if (lookupid != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.lookupid_.SetAllocated(lookupid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.lookupid_.IsDefault()) {
    _impl_.lookupid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gravity.ComponentServiceLookupResponsePB.lookupID)
}

// required string url = 2;
inline bool ComponentServiceLookupResponsePB::_internal_has_url() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool ComponentServiceLookupResponsePB::has_url() const {
  return _internal_has_url();
}
inline void ComponentServiceLookupResponsePB::clear_url() {
  _impl_.url_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& ComponentServiceLookupResponsePB::url() const {
  // @@protoc_insertion_point(field_get:gravity.ComponentServiceLookupResponsePB.url)
  return _internal_url();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ComponentServiceLookupResponsePB::set_url(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.url_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gravity.ComponentServiceLookupResponsePB.url)
}
inline std::string* ComponentServiceLookupResponsePB::mutable_url() {
  std::string* _s = _internal_mutable_url();
  // @@protoc_insertion_point(field_mutable:gravity.ComponentServiceLookupResponsePB.url)
  return _s;
}
inline const std::string& ComponentServiceLookupResponsePB::_internal_url() const {
  return _impl_.url_.Get();
}
inline void ComponentServiceLookupResponsePB::_internal_set_url(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.url_.Set(value, GetArenaForAllocation());
}
inline std::string* ComponentServiceLookupResponsePB::_internal_mutable_url() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.url_.Mutable(GetArenaForAllocation());
}
inline std::string* ComponentServiceLookupResponsePB::release_url() {
  // @@protoc_insertion_point(field_release:gravity.ComponentServiceLookupResponsePB.url)
  if (!_internal_has_url()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.url_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.url_.IsDefault()) {
    _impl_.url_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ComponentServiceLookupResponsePB::set_allocated_url(std::string* url) {
  if (url != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.url_.SetAllocated(url, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.url_.IsDefault()) {
    _impl_.url_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gravity.ComponentServiceLookupResponsePB.url)
}

// optional string domain_id = 3;
inline bool ComponentServiceLookupResponsePB::_internal_has_domain_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool ComponentServiceLookupResponsePB::has_domain_id() const {
  return _internal_has_domain_id();
}
inline void ComponentServiceLookupResponsePB::clear_domain_id() {
  _impl_.domain_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& ComponentServiceLookupResponsePB::domain_id() const {
  // @@protoc_insertion_point(field_get:gravity.ComponentServiceLookupResponsePB.domain_id)
  return _internal_domain_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ComponentServiceLookupResponsePB::set_domain_id(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000004u;
 _impl_.domain_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gravity.ComponentServiceLookupResponsePB.domain_id)
}
inline std::string* ComponentServiceLookupResponsePB::mutable_domain_id() {
  std::string* _s = _internal_mutable_domain_id();
  // @@protoc_insertion_point(field_mutable:gravity.ComponentServiceLookupResponsePB.domain_id)
  return _s;
}
inline const std::string& ComponentServiceLookupResponsePB::_internal_domain_id() const {
  return _impl_.domain_id_.Get();
}
inline void ComponentServiceLookupResponsePB::_internal_set_domain_id(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.domain_id_.Set(value, GetArenaForAllocation());
}
inline std::string* ComponentServiceLookupResponsePB::_internal_mutable_domain_id() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.domain_id_.Mutable(GetArenaForAllocation());
}
inline std::string* ComponentServiceLookupResponsePB::release_domain_id() {
  // @@protoc_insertion_point(field_release:gravity.ComponentServiceLookupResponsePB.domain_id)
  if (!_internal_has_domain_id()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* p = _impl_.domain_id_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.domain_id_.IsDefault()) {
    _impl_.domain_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ComponentServiceLookupResponsePB::set_allocated_domain_id(std::string* domain_id) {
  if (domain_id != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.domain_id_.SetAllocated(domain_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.domain_id_.IsDefault()) {
    _impl_.domain_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gravity.ComponentServiceLookupResponsePB.domain_id)
}

// optional uint32 registration_time = 4;
inline bool ComponentServiceLookupResponsePB::_internal_has_registration_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool ComponentServiceLookupResponsePB::has_registration_time() const {
  return _internal_has_registration_time();
}
inline void ComponentServiceLookupResponsePB::clear_registration_time() {
  _impl_.registration_time_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline uint32_t ComponentServiceLookupResponsePB::_internal_registration_time() const {
  return _impl_.registration_time_;
}
inline uint32_t ComponentServiceLookupResponsePB::registration_time() const {
  // @@protoc_insertion_point(field_get:gravity.ComponentServiceLookupResponsePB.registration_time)
  return _internal_registration_time();
}
inline void ComponentServiceLookupResponsePB::_internal_set_registration_time(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.registration_time_ = value;
}
inline void ComponentServiceLookupResponsePB::set_registration_time(uint32_t value) {
  _internal_set_registration_time(value);
  // @@protoc_insertion_point(field_set:gravity.ComponentServiceLookupResponsePB.registration_time)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace gravity

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ComponentServiceLookupResponsePB_2eproto
