// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ComponentLookupRequestPB.proto

#include "ComponentLookupRequestPB.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace gravity {
PROTOBUF_CONSTEXPR ComponentLookupRequestPB::ComponentLookupRequestPB(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.lookupid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.domain_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.type_)*/0} {}
struct ComponentLookupRequestPBDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ComponentLookupRequestPBDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ComponentLookupRequestPBDefaultTypeInternal() {}
  union {
    ComponentLookupRequestPB _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ComponentLookupRequestPBDefaultTypeInternal _ComponentLookupRequestPB_default_instance_;
}  // namespace gravity
static ::_pb::Metadata file_level_metadata_ComponentLookupRequestPB_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ComponentLookupRequestPB_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ComponentLookupRequestPB_2eproto = nullptr;

const uint32_t TableStruct_ComponentLookupRequestPB_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::gravity::ComponentLookupRequestPB, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::gravity::ComponentLookupRequestPB, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::gravity::ComponentLookupRequestPB, _impl_.lookupid_),
  PROTOBUF_FIELD_OFFSET(::gravity::ComponentLookupRequestPB, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::gravity::ComponentLookupRequestPB, _impl_.domain_id_),
  0,
  2,
  1,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, -1, sizeof(::gravity::ComponentLookupRequestPB)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::gravity::_ComponentLookupRequestPB_default_instance_._instance,
};

const char descriptor_table_protodef_ComponentLookupRequestPB_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\036ComponentLookupRequestPB.proto\022\007gravit"
  "y\"\254\001\n\030ComponentLookupRequestPB\022\020\n\010lookup"
  "ID\030\001 \002(\t\022@\n\004type\030\002 \001(\01622.gravity.Compone"
  "ntLookupRequestPB.RegistrationType\022\021\n\tdo"
  "main_id\030\003 \001(\t\")\n\020RegistrationType\022\010\n\004DAT"
  "A\020\000\022\013\n\007SERVICE\020\001BA\n\034com.aphysci.gravity."
  "protobufB\037ComponentLookupRequestContaine"
  "rH\001"
  ;
static ::_pbi::once_flag descriptor_table_ComponentLookupRequestPB_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ComponentLookupRequestPB_2eproto = {
    false, false, 283, descriptor_table_protodef_ComponentLookupRequestPB_2eproto,
    "ComponentLookupRequestPB.proto",
    &descriptor_table_ComponentLookupRequestPB_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_ComponentLookupRequestPB_2eproto::offsets,
    file_level_metadata_ComponentLookupRequestPB_2eproto, file_level_enum_descriptors_ComponentLookupRequestPB_2eproto,
    file_level_service_descriptors_ComponentLookupRequestPB_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ComponentLookupRequestPB_2eproto_getter() {
  return &descriptor_table_ComponentLookupRequestPB_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ComponentLookupRequestPB_2eproto(&descriptor_table_ComponentLookupRequestPB_2eproto);
namespace gravity {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ComponentLookupRequestPB_RegistrationType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ComponentLookupRequestPB_2eproto);
  return file_level_enum_descriptors_ComponentLookupRequestPB_2eproto[0];
}
bool ComponentLookupRequestPB_RegistrationType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr ComponentLookupRequestPB_RegistrationType ComponentLookupRequestPB::DATA;
constexpr ComponentLookupRequestPB_RegistrationType ComponentLookupRequestPB::SERVICE;
constexpr ComponentLookupRequestPB_RegistrationType ComponentLookupRequestPB::RegistrationType_MIN;
constexpr ComponentLookupRequestPB_RegistrationType ComponentLookupRequestPB::RegistrationType_MAX;
constexpr int ComponentLookupRequestPB::RegistrationType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class ComponentLookupRequestPB::_Internal {
 public:
  using HasBits = decltype(std::declval<ComponentLookupRequestPB>()._impl_._has_bits_);
  static void set_has_lookupid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_type(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_domain_id(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

ComponentLookupRequestPB::ComponentLookupRequestPB(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:gravity.ComponentLookupRequestPB)
}
ComponentLookupRequestPB::ComponentLookupRequestPB(const ComponentLookupRequestPB& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ComponentLookupRequestPB* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.lookupid_){}
    , decltype(_impl_.domain_id_){}
    , decltype(_impl_.type_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.lookupid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.lookupid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_lookupid()) {
    _this->_impl_.lookupid_.Set(from._internal_lookupid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.domain_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.domain_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_domain_id()) {
    _this->_impl_.domain_id_.Set(from._internal_domain_id(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.type_ = from._impl_.type_;
  // @@protoc_insertion_point(copy_constructor:gravity.ComponentLookupRequestPB)
}

inline void ComponentLookupRequestPB::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.lookupid_){}
    , decltype(_impl_.domain_id_){}
    , decltype(_impl_.type_){0}
  };
  _impl_.lookupid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.lookupid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.domain_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.domain_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ComponentLookupRequestPB::~ComponentLookupRequestPB() {
  // @@protoc_insertion_point(destructor:gravity.ComponentLookupRequestPB)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ComponentLookupRequestPB::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.lookupid_.Destroy();
  _impl_.domain_id_.Destroy();
}

void ComponentLookupRequestPB::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ComponentLookupRequestPB::Clear() {
// @@protoc_insertion_point(message_clear_start:gravity.ComponentLookupRequestPB)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.lookupid_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.domain_id_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.type_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ComponentLookupRequestPB::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required string lookupID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_lookupid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "gravity.ComponentLookupRequestPB.lookupID");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional .gravity.ComponentLookupRequestPB.RegistrationType type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::gravity::ComponentLookupRequestPB_RegistrationType_IsValid(val))) {
            _internal_set_type(static_cast<::gravity::ComponentLookupRequestPB_RegistrationType>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(2, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      // optional string domain_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_domain_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "gravity.ComponentLookupRequestPB.domain_id");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ComponentLookupRequestPB::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gravity.ComponentLookupRequestPB)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required string lookupID = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_lookupid().data(), static_cast<int>(this->_internal_lookupid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "gravity.ComponentLookupRequestPB.lookupID");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_lookupid(), target);
  }

  // optional .gravity.ComponentLookupRequestPB.RegistrationType type = 2;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_type(), target);
  }

  // optional string domain_id = 3;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_domain_id().data(), static_cast<int>(this->_internal_domain_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "gravity.ComponentLookupRequestPB.domain_id");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_domain_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gravity.ComponentLookupRequestPB)
  return target;
}

size_t ComponentLookupRequestPB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gravity.ComponentLookupRequestPB)
  size_t total_size = 0;

  // required string lookupID = 1;
  if (_internal_has_lookupid()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_lookupid());
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000006u) {
    // optional string domain_id = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_domain_id());
    }

    // optional .gravity.ComponentLookupRequestPB.RegistrationType type = 2;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ComponentLookupRequestPB::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ComponentLookupRequestPB::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ComponentLookupRequestPB::GetClassData() const { return &_class_data_; }


void ComponentLookupRequestPB::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ComponentLookupRequestPB*>(&to_msg);
  auto& from = static_cast<const ComponentLookupRequestPB&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gravity.ComponentLookupRequestPB)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_lookupid(from._internal_lookupid());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_domain_id(from._internal_domain_id());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.type_ = from._impl_.type_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ComponentLookupRequestPB::CopyFrom(const ComponentLookupRequestPB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gravity.ComponentLookupRequestPB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ComponentLookupRequestPB::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void ComponentLookupRequestPB::InternalSwap(ComponentLookupRequestPB* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.lookupid_, lhs_arena,
      &other->_impl_.lookupid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.domain_id_, lhs_arena,
      &other->_impl_.domain_id_, rhs_arena
  );
  swap(_impl_.type_, other->_impl_.type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ComponentLookupRequestPB::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ComponentLookupRequestPB_2eproto_getter, &descriptor_table_ComponentLookupRequestPB_2eproto_once,
      file_level_metadata_ComponentLookupRequestPB_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace gravity
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::gravity::ComponentLookupRequestPB*
Arena::CreateMaybeMessage< ::gravity::ComponentLookupRequestPB >(Arena* arena) {
  return Arena::CreateMessageInternal< ::gravity::ComponentLookupRequestPB >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
