// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceDirectoryRegistrationPB.proto

#include "ServiceDirectoryRegistrationPB.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace gravity {
PROTOBUF_CONSTEXPR ServiceDirectoryRegistrationPB::ServiceDirectoryRegistrationPB(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.url_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.component_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.domain_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.ip_address_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_.is_relay_)*/false
  , /*decltype(_impl_.timestamp_)*/uint64_t{0u}} {}
struct ServiceDirectoryRegistrationPBDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServiceDirectoryRegistrationPBDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServiceDirectoryRegistrationPBDefaultTypeInternal() {}
  union {
    ServiceDirectoryRegistrationPB _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServiceDirectoryRegistrationPBDefaultTypeInternal _ServiceDirectoryRegistrationPB_default_instance_;
}  // namespace gravity
static ::_pb::Metadata file_level_metadata_ServiceDirectoryRegistrationPB_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ServiceDirectoryRegistrationPB_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ServiceDirectoryRegistrationPB_2eproto = nullptr;

const uint32_t TableStruct_ServiceDirectoryRegistrationPB_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::gravity::ServiceDirectoryRegistrationPB, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::gravity::ServiceDirectoryRegistrationPB, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::gravity::ServiceDirectoryRegistrationPB, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::gravity::ServiceDirectoryRegistrationPB, _impl_.url_),
  PROTOBUF_FIELD_OFFSET(::gravity::ServiceDirectoryRegistrationPB, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::gravity::ServiceDirectoryRegistrationPB, _impl_.component_id_),
  PROTOBUF_FIELD_OFFSET(::gravity::ServiceDirectoryRegistrationPB, _impl_.domain_),
  PROTOBUF_FIELD_OFFSET(::gravity::ServiceDirectoryRegistrationPB, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::gravity::ServiceDirectoryRegistrationPB, _impl_.is_relay_),
  PROTOBUF_FIELD_OFFSET(::gravity::ServiceDirectoryRegistrationPB, _impl_.ip_address_),
  0,
  1,
  5,
  2,
  3,
  7,
  6,
  4,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 14, -1, sizeof(::gravity::ServiceDirectoryRegistrationPB)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::gravity::_ServiceDirectoryRegistrationPB_default_instance_._instance,
};

const char descriptor_table_protodef_ServiceDirectoryRegistrationPB_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n$ServiceDirectoryRegistrationPB.proto\022\007"
  "gravity\"\213\002\n\036ServiceDirectoryRegistration"
  "PB\022\n\n\002id\030\001 \001(\t\022\013\n\003url\030\002 \001(\t\022F\n\004type\030\003 \001("
  "\01628.gravity.ServiceDirectoryRegistration"
  "PB.RegistrationType\022\024\n\014component_id\030\004 \001("
  "\t\022\016\n\006domain\030\005 \001(\t\022\021\n\ttimestamp\030\006 \001(\004\022\020\n\010"
  "is_relay\030\007 \001(\010\022\022\n\nip_address\030\010 \001(\t\")\n\020Re"
  "gistrationType\022\010\n\004DATA\020\000\022\013\n\007SERVICE\020\001BG\n"
  "\034com.aphysci.gravity.protobufB%ServiceDi"
  "rectoryRegistrationContainerH\001"
  ;
static ::_pbi::once_flag descriptor_table_ServiceDirectoryRegistrationPB_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ServiceDirectoryRegistrationPB_2eproto = {
    false, false, 390, descriptor_table_protodef_ServiceDirectoryRegistrationPB_2eproto,
    "ServiceDirectoryRegistrationPB.proto",
    &descriptor_table_ServiceDirectoryRegistrationPB_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_ServiceDirectoryRegistrationPB_2eproto::offsets,
    file_level_metadata_ServiceDirectoryRegistrationPB_2eproto, file_level_enum_descriptors_ServiceDirectoryRegistrationPB_2eproto,
    file_level_service_descriptors_ServiceDirectoryRegistrationPB_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ServiceDirectoryRegistrationPB_2eproto_getter() {
  return &descriptor_table_ServiceDirectoryRegistrationPB_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ServiceDirectoryRegistrationPB_2eproto(&descriptor_table_ServiceDirectoryRegistrationPB_2eproto);
namespace gravity {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ServiceDirectoryRegistrationPB_RegistrationType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ServiceDirectoryRegistrationPB_2eproto);
  return file_level_enum_descriptors_ServiceDirectoryRegistrationPB_2eproto[0];
}
bool ServiceDirectoryRegistrationPB_RegistrationType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr ServiceDirectoryRegistrationPB_RegistrationType ServiceDirectoryRegistrationPB::DATA;
constexpr ServiceDirectoryRegistrationPB_RegistrationType ServiceDirectoryRegistrationPB::SERVICE;
constexpr ServiceDirectoryRegistrationPB_RegistrationType ServiceDirectoryRegistrationPB::RegistrationType_MIN;
constexpr ServiceDirectoryRegistrationPB_RegistrationType ServiceDirectoryRegistrationPB::RegistrationType_MAX;
constexpr int ServiceDirectoryRegistrationPB::RegistrationType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class ServiceDirectoryRegistrationPB::_Internal {
 public:
  using HasBits = decltype(std::declval<ServiceDirectoryRegistrationPB>()._impl_._has_bits_);
  static void set_has_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_url(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_type(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_component_id(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_domain(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_timestamp(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_is_relay(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_ip_address(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
};

ServiceDirectoryRegistrationPB::ServiceDirectoryRegistrationPB(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:gravity.ServiceDirectoryRegistrationPB)
}
ServiceDirectoryRegistrationPB::ServiceDirectoryRegistrationPB(const ServiceDirectoryRegistrationPB& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ServiceDirectoryRegistrationPB* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.id_){}
    , decltype(_impl_.url_){}
    , decltype(_impl_.component_id_){}
    , decltype(_impl_.domain_){}
    , decltype(_impl_.ip_address_){}
    , decltype(_impl_.type_){}
    , decltype(_impl_.is_relay_){}
    , decltype(_impl_.timestamp_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_id()) {
    _this->_impl_.id_.Set(from._internal_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.url_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.url_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_url()) {
    _this->_impl_.url_.Set(from._internal_url(), 
      _this->GetArenaForAllocation());
  }
  _impl_.component_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.component_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_component_id()) {
    _this->_impl_.component_id_.Set(from._internal_component_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.domain_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.domain_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_domain()) {
    _this->_impl_.domain_.Set(from._internal_domain(), 
      _this->GetArenaForAllocation());
  }
  _impl_.ip_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_ip_address()) {
    _this->_impl_.ip_address_.Set(from._internal_ip_address(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.type_, &from._impl_.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.timestamp_) -
    reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.timestamp_));
  // @@protoc_insertion_point(copy_constructor:gravity.ServiceDirectoryRegistrationPB)
}

inline void ServiceDirectoryRegistrationPB::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.id_){}
    , decltype(_impl_.url_){}
    , decltype(_impl_.component_id_){}
    , decltype(_impl_.domain_){}
    , decltype(_impl_.ip_address_){}
    , decltype(_impl_.type_){0}
    , decltype(_impl_.is_relay_){false}
    , decltype(_impl_.timestamp_){uint64_t{0u}}
  };
  _impl_.id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.url_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.url_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.component_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.component_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.domain_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.domain_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.ip_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ServiceDirectoryRegistrationPB::~ServiceDirectoryRegistrationPB() {
  // @@protoc_insertion_point(destructor:gravity.ServiceDirectoryRegistrationPB)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ServiceDirectoryRegistrationPB::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.id_.Destroy();
  _impl_.url_.Destroy();
  _impl_.component_id_.Destroy();
  _impl_.domain_.Destroy();
  _impl_.ip_address_.Destroy();
}

void ServiceDirectoryRegistrationPB::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ServiceDirectoryRegistrationPB::Clear() {
// @@protoc_insertion_point(message_clear_start:gravity.ServiceDirectoryRegistrationPB)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.id_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.url_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.component_id_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      _impl_.domain_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000010u) {
      _impl_.ip_address_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x000000e0u) {
    ::memset(&_impl_.type_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.timestamp_) -
        reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.timestamp_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ServiceDirectoryRegistrationPB::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "gravity.ServiceDirectoryRegistrationPB.id");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional string url = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_url();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "gravity.ServiceDirectoryRegistrationPB.url");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional .gravity.ServiceDirectoryRegistrationPB.RegistrationType type = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::gravity::ServiceDirectoryRegistrationPB_RegistrationType_IsValid(val))) {
            _internal_set_type(static_cast<::gravity::ServiceDirectoryRegistrationPB_RegistrationType>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(3, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      // optional string component_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_component_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "gravity.ServiceDirectoryRegistrationPB.component_id");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional string domain = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_domain();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "gravity.ServiceDirectoryRegistrationPB.domain");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional uint64 timestamp = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _Internal::set_has_timestamp(&has_bits);
          _impl_.timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool is_relay = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _Internal::set_has_is_relay(&has_bits);
          _impl_.is_relay_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string ip_address = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_ip_address();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "gravity.ServiceDirectoryRegistrationPB.ip_address");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ServiceDirectoryRegistrationPB::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gravity.ServiceDirectoryRegistrationPB)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string id = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_id().data(), static_cast<int>(this->_internal_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "gravity.ServiceDirectoryRegistrationPB.id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_id(), target);
  }

  // optional string url = 2;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_url().data(), static_cast<int>(this->_internal_url().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "gravity.ServiceDirectoryRegistrationPB.url");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_url(), target);
  }

  // optional .gravity.ServiceDirectoryRegistrationPB.RegistrationType type = 3;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_type(), target);
  }

  // optional string component_id = 4;
  if (cached_has_bits & 0x00000004u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_component_id().data(), static_cast<int>(this->_internal_component_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "gravity.ServiceDirectoryRegistrationPB.component_id");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_component_id(), target);
  }

  // optional string domain = 5;
  if (cached_has_bits & 0x00000008u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_domain().data(), static_cast<int>(this->_internal_domain().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "gravity.ServiceDirectoryRegistrationPB.domain");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_domain(), target);
  }

  // optional uint64 timestamp = 6;
  if (cached_has_bits & 0x00000080u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(6, this->_internal_timestamp(), target);
  }

  // optional bool is_relay = 7;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(7, this->_internal_is_relay(), target);
  }

  // optional string ip_address = 8;
  if (cached_has_bits & 0x00000010u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_ip_address().data(), static_cast<int>(this->_internal_ip_address().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "gravity.ServiceDirectoryRegistrationPB.ip_address");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_ip_address(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gravity.ServiceDirectoryRegistrationPB)
  return target;
}

size_t ServiceDirectoryRegistrationPB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gravity.ServiceDirectoryRegistrationPB)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional string id = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_id());
    }

    // optional string url = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_url());
    }

    // optional string component_id = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_component_id());
    }

    // optional string domain = 5;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_domain());
    }

    // optional string ip_address = 8;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_ip_address());
    }

    // optional .gravity.ServiceDirectoryRegistrationPB.RegistrationType type = 3;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 +
        ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
    }

    // optional bool is_relay = 7;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 + 1;
    }

    // optional uint64 timestamp = 6;
    if (cached_has_bits & 0x00000080u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_timestamp());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ServiceDirectoryRegistrationPB::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ServiceDirectoryRegistrationPB::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ServiceDirectoryRegistrationPB::GetClassData() const { return &_class_data_; }


void ServiceDirectoryRegistrationPB::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ServiceDirectoryRegistrationPB*>(&to_msg);
  auto& from = static_cast<const ServiceDirectoryRegistrationPB&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gravity.ServiceDirectoryRegistrationPB)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_id(from._internal_id());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_url(from._internal_url());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_component_id(from._internal_component_id());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_set_domain(from._internal_domain());
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_internal_set_ip_address(from._internal_ip_address());
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.type_ = from._impl_.type_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.is_relay_ = from._impl_.is_relay_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.timestamp_ = from._impl_.timestamp_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ServiceDirectoryRegistrationPB::CopyFrom(const ServiceDirectoryRegistrationPB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gravity.ServiceDirectoryRegistrationPB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServiceDirectoryRegistrationPB::IsInitialized() const {
  return true;
}

void ServiceDirectoryRegistrationPB::InternalSwap(ServiceDirectoryRegistrationPB* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.id_, lhs_arena,
      &other->_impl_.id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.url_, lhs_arena,
      &other->_impl_.url_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.component_id_, lhs_arena,
      &other->_impl_.component_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.domain_, lhs_arena,
      &other->_impl_.domain_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ip_address_, lhs_arena,
      &other->_impl_.ip_address_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ServiceDirectoryRegistrationPB, _impl_.timestamp_)
      + sizeof(ServiceDirectoryRegistrationPB::_impl_.timestamp_)
      - PROTOBUF_FIELD_OFFSET(ServiceDirectoryRegistrationPB, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ServiceDirectoryRegistrationPB::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ServiceDirectoryRegistrationPB_2eproto_getter, &descriptor_table_ServiceDirectoryRegistrationPB_2eproto_once,
      file_level_metadata_ServiceDirectoryRegistrationPB_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace gravity
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::gravity::ServiceDirectoryRegistrationPB*
Arena::CreateMaybeMessage< ::gravity::ServiceDirectoryRegistrationPB >(Arena* arena) {
  return Arena::CreateMessageInternal< ::gravity::ServiceDirectoryRegistrationPB >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
